### ISSUE TITLE
项目启动不了

### ISSUE THREAD

**Issue by xu-Aurora** [pansyjs/react-admin#169]
<img width="1052" alt="截屏2020-06-03 上午9 34 54" src="https://user-images.githubusercontent.com/35291465/83585872-88a17880-a57d-11ea-82cb-23ac12ae566e.png">

**Comment by wangxingkang** [comment]
新版未写完 可以先试一下  master 分支

**Comment by wangxingkang** [comment]
最近有点忙  欢迎 PR

**Comment by wangxingkang** [comment]
新版本会在年内发布
